name: pre-commit-main

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: Komorebi-AI/github-actions/.github/workflows/pre-commit-uv.yml@main
    with:
      uv-version: 0.8.0
