name: pre-commit-main

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run with tmate debugging enabled"
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: Komorebi-AI/github-actions/.github/workflows/pre-commit-uv.yml@main
    with:
      uv-version: 0.8.0
      debug-enabled: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
