name: pre-commit-pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # required to grab the history of the PR
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: v0.29.0
          cache: true
          environments: dev
          manifest-path: pyproject.toml
      - uses: pre-commit/action@v3.0.1
        with:
          # Ejecutar solo en ficheros que hayan cambiado https://github.com/pre-commit/action/issues/7
          extra_args: --color=always --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
